### ISSUE TITLE
[bug] Rollup failed to resolve import "/src/style/mystyle.css" from "index.html".

### ISSUE THREAD

**Issue by peacheychen** [Creader-project/Creader-website#1]
![image](https://user-images.githubusercontent.com/16849339/146646008-7f66c0b3-83bc-4ca8-afd7-9081e16b46e5.png)
when I run 
```
npm build 
```  
it showed the above error

**Comment by timothyshen** [comment]
@peacheychen This should be resolved now. Pushed the CSS file now
